const version = require('../package.json').version

export const NEXUS_PRISMA_HEADER = `\
/**
 * This file was automatically generated by nexus-prisma@${version}
 * Do not make changes to this file directly
 */`
