/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as photon from "@generated/photon"
import { core } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AuthorCreateManyWithoutAuthorsInput: { // input type
    connect?: NexusGenInputs['AuthorWhereUniqueInput'][] | null; // [AuthorWhereUniqueInput!]
    create?: NexusGenInputs['AuthorCreateWithoutBlogInput'][] | null; // [AuthorCreateWithoutBlogInput!]
  }
  AuthorCreateOneWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['AuthorWhereUniqueInput'] | null; // AuthorWhereUniqueInput
    create?: NexusGenInputs['AuthorCreateWithoutPostsInput'] | null; // AuthorCreateWithoutPostsInput
  }
  AuthorCreateWithoutBlogInput: { // input type
    name?: string | null; // String
    posts?: NexusGenInputs['PostCreateManyWithoutPostsInput'] | null; // PostCreateManyWithoutPostsInput
  }
  AuthorCreateWithoutPostsInput: { // input type
    blog: NexusGenInputs['BlogCreateOneWithoutBlogInput']; // BlogCreateOneWithoutBlogInput!
    name?: string | null; // String
  }
  AuthorWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  BlogCreateInput: { // input type
    authors?: NexusGenInputs['AuthorCreateManyWithoutAuthorsInput'] | null; // AuthorCreateManyWithoutAuthorsInput
    name: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutPostsInput'] | null; // PostCreateManyWithoutPostsInput
    viewCount: number; // Int!
  }
  BlogCreateOneWithoutBlogInput: { // input type
    connect?: NexusGenInputs['BlogWhereUniqueInput'] | null; // BlogWhereUniqueInput
    create?: NexusGenInputs['BlogCreateWithoutAuthorsInput'] | null; // BlogCreateWithoutAuthorsInput
  }
  BlogCreateWithoutAuthorsInput: { // input type
    name: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutPostsInput'] | null; // PostCreateManyWithoutPostsInput
    viewCount: number; // Int!
  }
  BlogWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  PostCreateManyWithoutPostsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    create?: NexusGenInputs['PostCreateWithoutBlogInput'][] | null; // [PostCreateWithoutBlogInput!]
  }
  PostCreateWithoutBlogInput: { // input type
    author?: NexusGenInputs['AuthorCreateOneWithoutAuthorInput'] | null; // AuthorCreateOneWithoutAuthorInput
    tags?: NexusGenInputs['PostCreatetagsInput'] | null; // PostCreatetagsInput
    title: string; // String!
  }
  PostCreatetagsInput: { // input type
    set?: string[] | null; // [String!]
  }
  PostWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
}

export interface NexusGenRootTypes {
  Author: photon.Author;
  Blog: photon.Blog;
  CustomPost: { // root type
    id: number; // Int!
    tags: string[]; // [String!]!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  AuthorCreateManyWithoutAuthorsInput: NexusGenInputs['AuthorCreateManyWithoutAuthorsInput'];
  AuthorCreateOneWithoutAuthorInput: NexusGenInputs['AuthorCreateOneWithoutAuthorInput'];
  AuthorCreateWithoutBlogInput: NexusGenInputs['AuthorCreateWithoutBlogInput'];
  AuthorCreateWithoutPostsInput: NexusGenInputs['AuthorCreateWithoutPostsInput'];
  AuthorWhereUniqueInput: NexusGenInputs['AuthorWhereUniqueInput'];
  BlogCreateInput: NexusGenInputs['BlogCreateInput'];
  BlogCreateOneWithoutBlogInput: NexusGenInputs['BlogCreateOneWithoutBlogInput'];
  BlogCreateWithoutAuthorsInput: NexusGenInputs['BlogCreateWithoutAuthorsInput'];
  BlogWhereUniqueInput: NexusGenInputs['BlogWhereUniqueInput'];
  PostCreateManyWithoutPostsInput: NexusGenInputs['PostCreateManyWithoutPostsInput'];
  PostCreateWithoutBlogInput: NexusGenInputs['PostCreateWithoutBlogInput'];
  PostCreatetagsInput: NexusGenInputs['PostCreatetagsInput'];
  PostWhereUniqueInput: NexusGenInputs['PostWhereUniqueInput'];
}

export interface NexusGenFieldTypes {
  Author: { // field return type
    blog: NexusGenRootTypes['Blog']; // Blog!
    id: number; // Int!
    name: string | null; // String
    posts: NexusGenRootTypes['CustomPost'][] | null; // [CustomPost!]
  }
  Blog: { // field return type
    authors: NexusGenRootTypes['Author'][] | null; // [Author!]
    createdAt: any; // DateTime!
    id: number; // Int!
    name: string; // String!
    posts: NexusGenRootTypes['CustomPost'][] | null; // [CustomPost!]
    updatedAt: any; // DateTime!
    viewCount: number; // Int!
  }
  CustomPost: { // field return type
    id: number; // Int!
    tags: string[]; // [String!]!
    title: string; // String!
  }
  Mutation: { // field return type
    createOneBlog: NexusGenRootTypes['Blog']; // Blog!
  }
  Query: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    blogs: NexusGenRootTypes['Blog'][] | null; // [Blog!]
    findManyAuthor: NexusGenRootTypes['Author'][] | null; // [Author!]
    findManyPost: NexusGenRootTypes['CustomPost'][] | null; // [CustomPost!]
  }
}

export interface NexusGenArgTypes {
  Author: {
    posts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  Blog: {
    authors: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    posts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  Mutation: {
    createOneBlog: { // args
      data: NexusGenInputs['BlogCreateInput']; // BlogCreateInput!
    }
  }
  Query: {
    blog: { // args
      where: NexusGenInputs['BlogWhereUniqueInput']; // BlogWhereUniqueInput!
    }
    blogs: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    findManyAuthor: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    findManyPost: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Author" | "Blog" | "CustomPost" | "Mutation" | "Query";

export type NexusGenInputNames = "AuthorCreateManyWithoutAuthorsInput" | "AuthorCreateOneWithoutAuthorInput" | "AuthorCreateWithoutBlogInput" | "AuthorCreateWithoutPostsInput" | "AuthorWhereUniqueInput" | "BlogCreateInput" | "BlogCreateOneWithoutBlogInput" | "BlogCreateWithoutAuthorsInput" | "BlogWhereUniqueInput" | "PostCreateManyWithoutPostsInput" | "PostCreateWithoutBlogInput" | "PostCreatetagsInput" | "PostWhereUniqueInput";

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: {};
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}