name: ci

on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn -s test
